name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

    - name: Make gradlew executable
      # If gradlew is present but not executable, this fixes it.
      run: |
        if [ -f ./gradlew ]; then
          chmod +x ./gradlew
          echo "gradlew set as executable"
        else
          echo "gradlew not found in repo, continuing"
        fi

    - name: Build Debug APK
      # Use wrapper if present; wrapper will be used after chmod.
      run: |
        if [ -f ./gradlew ]; then
          ./gradlew assembleDebug --no-daemon
        else
          echo "gradlew not found — attempting to run Gradle via installed Gradle (may fail if not available)"
          gradle assembleDebug --no-daemon
        fi

    - name: Upload APK artifact (if exists)
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
