name: Build APK (no wrapper)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

    - name: Install Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.4'   # hoặc bỏ để lấy latest

    - name: Build debug APK using installed Gradle
      run: gradle assembleDebug --no-daemon

    - name: Upload APK artifact (if exists)
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
